< {%
   request.variables.set("access-token", client.global.get("access-token"))
%}
GRAPHQL {{urlPrefix}}/graphql
Authorization: Bearer {{access-token}}

{
  getMedia(media: "media") {
    id
    metadata {
      takenAt
    }
  }
}
