POST {{urlPrefix}}/api/auth/signin
Content-Type: application/json

{
  "email": "{{admin.email}}",
  "password": "{{admin.password}}"
}

> {%
    client.global.set("admin-access-token", response.body["accessToken"]);
%}
