name: Release Jar and Docker image

on:
  push:
    tags:
      - '*'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: tag
        run: echo ::set-output name=NAME::${GITHUB_REF/refs\/tags\//}

      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Use tag name as IDS backend version and Docker tag name
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          include: "build.gradle"
          find: '"0.0.0"'
          replace: '"${{ steps.tag.outputs.NAME }}"'

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Build IDS backend
        run: ./gradlew bootJar

      - name: Create check sum file
        run: sha512sum *.jar > ids-backend-SHA512.txt
        working-directory: build/libs

      - name: Create GitHub release
        id: release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.tag.outputs.NAME }}
          draft: true

      - name: Upload Jar to release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: build/libs/ids-backend-${{ steps.tag.outputs.NAME }}.jar
          asset_name: ids-backend-${{ steps.tag.outputs.NAME }}.jar
          asset_content_type: application/octet-stream

      - name: Upload check sum file to release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: build/libs/ids-backend-SHA512.txt
          asset_name: ids-backend-SHA512.txt
          asset_content_type: text/plain

      - name: Publish release with notes
        uses: cyosp/publish-release-with-notes@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.release.outputs.id }}
          version: ${{ steps.tag.outputs.NAME }}
          notes: ${{ github.workspace }}/RELEASE-NOTES.md

      - name: Setup Docker QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: linux/amd64,linux/arm/v7

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Create context for Docker build and push action
        run: ./gradlew docker

      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image to registry
        uses: docker/build-push-action@v2.7.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: build/docker
          file: Dockerfile
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: cyosp/${{ github.event.repository.name }}:${{ steps.tag.outputs.NAME }}
